### ISSUE TITLE
VM fails in installRsyncInVM step

### ISSUE THREAD

**Issue by tbvdm** [vmactions/dragonflybsd-vm#4]
My recent DragonFly jobs have failed as follows. Let me know if you need more information.

```
2024-02-09T12:32:12.2933302Z exec shell: bash run.sh installRsyncInVM
2024-02-09T12:32:12.2946944Z [command]/usr/bin/bash
2024-02-09T12:32:12.3031398Z Config file: dragonflybsd-6.4.0.conf
2024-02-09T12:32:12.4921667Z Updating Avalon repository catalogue...
2024-02-09T12:32:13.8913290Z Fetching meta.conf: . done
2024-02-09T12:32:22.2450361Z Fetching packagesite.pkg: .......... done
2024-02-09T12:32:24.2577529Z Processing entries: .......... done
2024-02-09T12:32:24.2578229Z Avalon repository update completed. 31890 packages processed.
2024-02-09T12:32:24.7568036Z All repositories are up to date.
2024-02-09T12:32:24.7691494Z New version of pkg detected; it needs to be installed first.
2024-02-09T12:32:24.7695397Z The following 1 package(s) will be affected (of 0 checked):
2024-02-09T12:32:24.7696254Z 
2024-02-09T12:32:24.7698074Z Installed packages to be UPGRADED:
2024-02-09T12:32:24.7699187Z 	pkg: 1.19.2 -> 1.20.9 [Avalon]
2024-02-09T12:32:24.7700332Z 
2024-02-09T12:32:24.7700870Z Number of packages to be upgraded: 1
2024-02-09T12:32:24.7703980Z 
2024-02-09T12:32:24.7705075Z The process will require 1 MiB more space.
2024-02-09T12:32:24.7705973Z 3 MiB to be downloaded.
2024-02-09T12:32:31.8155054Z [1/1] Fetching pkg-1.20.9.pkg: .......... done
2024-02-09T12:32:31.8407259Z Checking integrity... done (0 conflicting)
2024-02-09T12:32:31.8443148Z [1/1] Upgrading pkg from 1.19.2 to 1.20.9...
2024-02-09T12:32:32.0910886Z [1/1] Extracting pkg-1.20.9: .......... done
2024-02-09T12:32:32.1407830Z You may need to manually remove /usr/local/etc/pkg.conf if it is no longer needed.
2024-02-09T12:32:32.1474276Z Updating Avalon repository catalogue...
2024-02-09T12:32:32.8974791Z pkg: An error occured while fetching package
2024-02-09T12:32:33.6473678Z pkg: An error occured while fetching package
2024-02-09T12:32:33.6478334Z repository Avalon has no meta file, using default settings
2024-02-09T12:32:34.1340150Z pkg: An error occured while fetching package
2024-02-09T12:32:34.5607972Z pkg: An error occured while fetching package
2024-02-09T12:32:34.5645911Z Unable to update repository Avalon
2024-02-09T12:32:34.5649452Z Error updating repositories!
2024-02-09T12:32:34.5688739Z exec shell: bash run.sh showDebugInfo
```

**Comment by dgsga** [comment]
Exactly the same error here. Likewise.

**Comment by Neilpang** [comment]
I think it's a problem from the dragonflybsd side.
the new version `pkg` tool is not working anymore.

 

![image](https://github.com/vmactions/dragonflybsd-vm/assets/8305679/f52d6259-9187-4b31-a80b-a5e4a7a93c43)

**Comment by Midar** [comment]
Can confirm, it's currently breaking all my tests.

**Comment by tbvdm** [comment]
I can reproduce this on a freshly installed DragonFly 6.4.0 release. I don't know what the proper fix is supposed to be, but I was able to work around this by creating a symlink first:

```
ln -s /usr/local/etc/ssl/cert.pem /etc/ssl/
pkg install -y rsync
```

This may be related to the fact that pkg 1.20.0 [switched from libfetch to libcurl](https://github.com/freebsd/pkg/releases/tag/1.20.0).

**Comment by Neilpang** [comment]
fixed, try again.

**Comment by dgsga** [comment]
@neilpang, thanks for working on this . Unfortunately I am still getting the same error with v1.0.3. Should I be using v1?

**Comment by Neilpang** [comment]
please use `v1`,  or just use `v1.0.4`
